---
- name: Download distribution
  get_url:
    url: "{{ download_url }}"
    dest: /opt/{{ dist_file }}
    checksum: "{{ dist_checksum }}"

- name: Extract archive
  unarchive: src=/opt/{{ dist_file }} dest=/opt copy=no

- name: Change ownership of installation
  file:
    path: "{{ install_dir }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    state: directory
    recurse: yes

- name: Make installation symlink
  file:
    src: "{{ install_dir }}"
    dest: "{{ install_dir_symlink }}"
    state: link
